#*******************************************************
# Makefile for CST 352 Lab 1
#
# Author: Samuel Huff
# Filename: Makefile
# Date Created: 3/31/2016
# Modifications:
#
#*******************************************************
CC=gcc
COPTS=-g -o

all: buddy

clean: 
	rm -f buddy *~

buddy: buddy.c
	$(CC) $(COPTS) buddy buddy.c
