#*******************************************************
# Makefile for CST 352 Lab 3
#
# Author: Samuel Huff
# Filename: Makefile
# Date Created: 3/31/2016
# Modifications:
#
#*******************************************************
CC=stacklc

all: syscalls

clean: 
	rm -f syscalls.sl
	rm -f syscalls.slb

syscalls:
	$(CC) syscalls.c -boot
